# ===============================
# CONFIGURARE SERVER
# ===============================
server.port=8084
spring.application.name=statistici-service

# ===============================
# CONFIGURARE SWAGGER (OPENAPI)
# ===============================
# Interfata Swagger va fi disponibila la: http://localhost:8084/swagger-ui/index.html
springdoc.swagger-ui.path=/swagger-ui.html