# ===============================
# CONFIGURARE SERVER
# ===============================
# Folosim portul 8083 deoarece 8080, 8081 ?i 8082 sunt ocupate
server.port=8083

# Numele aplica?iei (util pentru API Gateway / Eureka)
spring.application.name=export-service

# ===============================
# CONFIGURARE SWAGGER (OPENAPI)
# ===============================
# Interfata Swagger va fi disponibila la: http://localhost:8083/swagger-ui/index.html
springdoc.swagger-ui.path=/swagger-ui.html