# ===============================
# CONFIGURARE SERVER
# ===============================
# Schimb?m pe 8082 pentru a rula simultan cu Utilizatori (8081) ?i Zboruri (8080?)
server.port=8082

# ===============================
# CONFIGURARE BAZA DE DATE MYSQL
# ===============================
# Folosim baza de date pentru bilete creat? anterior
spring.datasource.url=jdbc:mysql://localhost:3306/db_ps_aeroport_big_project_bilete?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# CONFIGURARE JPA / HIBERNATE
# ===============================
# L?s?m pe 'none' pentru c? am creat tabelele manual prin scriptul SQL
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# ===============================
# CONFIGURARE SWAGGER (OPENAPI)
# ===============================
# Swagger va fi disponibil la: http://localhost:8082/swagger-ui.html
springdoc.swagger-ui.path=/swagger-ui.html