# ===============================
# CONFIGURARE SERVER
# ===============================
server.port=8080

# ===============================
# CONFIGURARE BAZA DE DATE MYSQL
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/db_ps_aeroport_big_project_zboruri?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# CONFIGURARE JPA / HIBERNATE
# ===============================
# Deoarece ai creat tabelele manual prin script SQL, setam ddl-auto pe 'none' sau 'validate'
# 'none' inseamna ca Spring nu se atinge de structura tabelelor tale.
spring.jpa.hibernate.ddl-auto=none

# Afisarea query-urilor SQL in consola (foarte util pentru debugging)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Setarea dialectului pentru MySQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ===============================
# CONFIGURARE SWAGGER (OPENAPI)
# ===============================
# Interfata Swagger va fi disponibila la: http://localhost:8080/swagger-ui/index.html
springdoc.swagger-ui.path=/swagger-ui.html